### ISSUE TITLE
Displaying amount of stations in the last updated lists

### ISSUE THREAD

**Issue by NightPurrer** [TomaszGasior/RadioLista-v3#227]
Currently, in the category of recently updated lists, the number of stations for each of items isn't displayed.

**Comment by TomaszGasior** [comment]
Items contained on "all lists" page (https://radiolista.pl/all-lists) show all data about each list: last updated date, amount of stations, unit (kHz vs MHz) and author's username. Items can be sorted by number of stations or last update date, or unit. This resource can be accessed using link in the site footer ("All lists"). 

From the other hand, "Last modified lists" section of the home page does not provide all information about each list. Only last updated time (in relative form, like "two hours ago") is shown.

The reason for this inconsistency is aesthetics. "All radio tables" page shows each radio list as one big row of information so there is enough visual space for all details. From the other hand, homepage "Last modified lists"  list shows items as small blocks. "All radio tables" page is designed for purpose of detailed analysis of all lists in RadioLista. Last modified lists on the homepage is used to show what's going on in the RadioLista, and what users are doing right now. Homepage is not designed to be source of detailed analysis or for searching by reading all lists details.

Because of this difference I would like to keep homepage section simpler and with less details. However, adding just radio stations counter to each item of homepage's section with last updated lists would be fine. I will add this change to upcoming new release.
